# This rule is not used by the project juicefs-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the juicefs.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: juicefs-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronsync-editor-role
rules:
- apiGroups:
  - juicefs.io
  resources:
  - cronsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juicefs.io
  resources:
  - cronsyncs/status
  verbs:
  - get
