apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: default
type: Opaque
stringData:
  name: juicefs-xx
  token: xx
  access-key: xx
  secret-key: xx
---
apiVersion: juicefs.io/v1
kind: CacheGroup
metadata:
  name: cachegroup-sample
  namespace: default
spec:
  # Number of desired cache-group pods.
  # If not specified, a cache-group pod will be created on all nodes that match `worker.template.nodeSelector`
  # If this field is used, it must be ensured that pod-ip can be fixed, and the cache disk can follow the pod to other nodes.
  # replicas: 10
  secretRef:
    name: juicefs-secret
  # Duration for new node to join cluster with group-backup option
  backupDuration: "10m"
  # Maximum time to wait for data migration when deleting
  waitingDeletedMaxDuration: "1h"
  updateStrategy:
    # support：
    # - RollingUpdate: default policy
    # - OnDelete: only manually delete the worker pod, the controller will create a new one
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  worker:
    template:
      nodeSelector:
        juicefs.io/cg-worker: "true"
      image: juicedata/mount:ee-5.1.1-1faf43b
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1
          memory: 1Gi
      cacheDirs:
        - path: /var/jfsCache-0
          type: HostPath
        # - type: VolumeClaimTemplates
        #   volumeClaimTemplate:
        #     metadata:
        #       name: jfs
        #     spec:
        #       accessModes:
        #       - ReadWriteOnce
        #       resources:
        #         requests:
        #           storage: 20Gi
        #       storageClassName: alicloud-disk-topology-alltype
      opts:
        - group-weight=100
        - cache-size=204800
        - free-space-ratio=0.01
    overwrite:
      - nodes:
          - k8s-03
        opts:
          - group-weight=50
          - cache-size=102400
          - free-space-ratio=0.01
        cacheDirs:
        - path: /var/jfsCache-1
          type: HostPath
        - path: /var/jfsCache-2
          type: HostPath
      - nodeSelector:
          k8s/instance-type: c5.large
        opts:
          - group-weight=10
          - cache-size=1024