apiVersion: juicefs.io/v1
kind: CronSync
metadata:
  labels:
    app.kubernetes.io/name: juicefs-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronsync-sample
spec:
  # TODO(user): Add fields here
